### ISSUE TITLE
Task List 16.10.2024

### ISSUE THREAD

**Issue by rudolf101** [rudolf101/RISCify#10]
# Team Task List

## Task List

- **Frontend**:
    - [x] #6 @ndreuu 

- **Research**:
    - [x] #4 @KonovkinaEA @Антон Самарин
    - [x] #7 @CaesiumFox 
    - [x] #8 @ndreuu 
    - [x] #9 @rudolf101 

- **Infrastructure**
   - [x] Init GitHub Wiki @rudolf101 
   - [x] Task list @rudolf101 
   - [x] Project requirements @rudolf101
